branch: main
deployment_tasks:
  - export DEPLOYPATH=/home/username/public_html/
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp -R css $DEPLOYPATH
  - /bin/cp -R js $DEPLOYPATH
  - /bin/cp -R images $DEPLOYPATH
